### ISSUE TITLE
the uevent_helper, is it userful under andorid 6.0.1

### ISSUE THREAD

**Issue by pppdddxxx** [matteoserva/dirtycow-arm32#3]
thanks for your poc about dirtycow!
I see you  raise a point about uevent_helper, is it userful under andorid 6.0.1,thanks!

**Comment by matteoserva** [comment]
Yes. I used it on my phone to start the su daemon at boot. I hadn't had time to write everything.
I wanted to get a clean root without using dirtycow because dirtycow makes some kernel features unusable.

Basically I first used the dirtycow exploit to get root acces and created the sepolicy file to have write permission on everything.
Then I searched for a partition with suid permissions with the command
"mount | grep  rw | grep -v nosuid | grep -v noexec"
My device (samsung note 4) has one at /data/enc_user.
I placed my program there and assigned it cap_setuid permission (you have to compile setcap for android).

adb can execute suid programs, so now I can use it to become root.

Sadly adb can become root but it is still limited by the capability bounding set.

Since I already control the sepolicy, I allowed it to write to uevent_helper. The uevent_helper is a script I can control and I used it to spawn my superDaemon as root user, with the privileged selinux context, with the full set of posix capabilities.

To connect to adb from the phone itself, I had to make it reachable via tcp, so I can connect to it and send commands.

**Comment by pppdddxxx** [comment]
OK！
now,i have a question: you know the init file can write the uevent_helper, when i write a script into uevent_helper by init file, I can't see my script is executed,is  there other security mechanism that prevent the phone to  execute the script?thanks.

**Comment by matteoserva** [comment]
can you read it back? 
If so: first make sure your script is executable (chmod +x script) and starts with "#!/system/bin/sh". Then watch the logs. You should both check dmesg and logcat :  "dmesg | grep avc" and "logcat | grep avc". The script will be called in the kernel context so make sure it has the proper selinux permission to do what you need. Remember that your script will be called many times very quickly, the first thing my script does is writing "" into uevent_helper to disable further executions, then it spawns the root daemon.

**Comment by pppdddxxx** [comment]
thanks for your help!
now, I have another question, I have rise up a daemon su that has root pri. but when I execute file su which located at /data/local/tmp, it failed! is it because of selinux?thanks

**Comment by matteoserva** [comment]
* did you try executing "chmod +x su"?
* did you compile it with the android toolchain?
* can you run something else in /system/bin?
* are you using my superdaemon?
* are you on samsung?
